service: magic-eightball

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  profile: serverless
  region: us-east-1
  environment:
    SLACK_TOKEN: ${ssm:slackToken}

functions:
  app:
    handler: server.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
